### ISSUE TITLE
neovim rpc

### ISSUE THREAD

**Issue by diyhome** [leoatchina/leoatchina-vim#1]
你好，在我使用你这个配置文件时出现
```
[vim-hug-neovim-rpc] failed executing: pythonx import neovim
[vim-hug-neovim-rpc] Vim(pythonx):Traceback (most recent call last):
```
请问怎么关闭？
> opensuse leap 15.0 
> VIM - Vi IMproved 8.0 (2016 Sep 12)

**Comment by leoatchina** [comment]
pip3 install neovim    first ? sorry for reply so later

**Comment by leoatchina** [comment]
I have made lots of commits since you pr , and you can alse do `git pull`, and `./update.sh`.
I will rewrite the readme for detail uses.

**Comment by diyhome** [comment]
Think you help me to solve this problem
