### ISSUE TITLE
Error detected while processing /home/***/.vimrc.local

### ISSUE THREAD

**Issue by Sujiyi** [leoatchina/leoatchina-vim#5]
**Hello，The following error occurred during installation, what should I do?**

Error detected while processing /home/***/.vimrc.local:
line    6:
E117: Unknown function: vundle#begin
line   11:
E492: Not an editor command: Plugin 'VundleVim/Vundle.vim'
line   16:
E492: Not an editor command: Plugin 'tpope/vim-fugitive'
line   20:
E492: Not an editor command: Plugin 'git://git.wincent.com/command-t.git'
line   22:
E492: Not an editor command: Plugin 'file:///home/gmarik/path/to/plugin'
line   25:
E492: Not an editor command: Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
line   31:
E117: Unknown function: vundle#end
Press ENTER or type command to continue

**Comment by leoatchina** [comment]
I donot use vundle for plug manager， so plz check if you use my config?

**Comment by leoatchina** [comment]
oh， it looks like that your .vim.local include something not compatible with my config， plz look at the .vimrc.local.default in this repo

**Comment by leoatchina** [comment]
sorry, my english is poor, it seems you have just use .vimrc.local that is from spf13's conf, my plug manager is vim-plug, which is quitely diffent from vundle,  so I advice you to delete your .vimrc.local
