### ISSUE TITLE
get Error:

### ISSUE THREAD

**Issue by shouhuori** [leoatchina/leoatchina-vim#7]
error message:
```
Error detected while processing /Users/zhichou/.vimrc:
line   10:
E334: Menu not found: File.New\ Tab
```
OS:macOSX 10.14.4
vim:8.1.950

**Comment by leoatchina** [comment]
do you use vim in terminal or macvim?  this config is for macvim,not for vim in terminal

**Comment by shouhuori** [comment]
@leoatchina  thanks! I got it. 😁
